;MOV R1,#10H ;NO OF TIMES TO RUN
;MOV R2,#3H ; NO TO ADD
;MOV A,#00H ; CLEAR A

;LOOP: ADD A,R2
;MOV R3,A ; TOTAL SUM
;DJNZ R1,LOOP

MOV R2,#10H ; NO OF ELEMENTS
MOV R1,#3H; NO TO ADD


MOV R0,#0A0H ; START ADDRESS
LOOP: MOV A, @R0
ADD A,R1
MOV @R0,A
INC R0
DJNZ R2,LOOP